version: '3'

services:
  backend:
    image: janlukac/agilypet-backend:0.3
    ports:
      - "3001:3001"

  frontend:
    image: janlukac/agilypet-frontend:0.7
    ports:
      - "3000:3000"
    depends_on:
      - backend
  